- name: Create .kube directory
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu

- name: Copy admin.conf to user kubeconfig
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu

- name: Fetch kubeconfig to local machine
  fetch:
    src: /home/ubuntu/.kube/config
    dest: ~/.kube/config-k8s-storage-lab
    flat: yes
