apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: beegfs-scratch
provisioner: beegfs.csi.netapp.com
parameters:
  sysMgmtdHost: <BACKEND_PRIVATE_IP>
  volDirBasePath: /k8s/dynamic
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
