# -*- mode: ruby -*-
# vi: set ft=ruby :

CLUSTER_NAME = "k8s-rocky9-minikube"

Vagrant.configure("2") do |config|
  config.vm.define "minikube-master" do |node|
    node.vm.box = "bento/rockylinux-9"
    node.vm.box_version = "202510.26.0"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "minikube-master"
      vb.memory = 16000
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      vb.customize ["modifyvm", :id, "--groups", "/#{CLUSTER_NAME}"]
    end
    node.vm.hostname = "minikube-master"
    node.vm.network "private_network", ip: "192.168.81.10"
    node.vm.network "forwarded_port", guest: 22, host: 22222, auto_correct: true, id: "ssh"
    node.vm.provision "shell", inline: "sudo dnf update -y"
    node.vm.provision "shell", path: "./scripts/cluster/minikube.sh", privileged: false
    #node.vm.provision "shell", path: "./scripts/addons/kubevirt/kubevirt_install.sh", privileged: false
  end
end
