---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-cephfs
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ceph-cephfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-cephfs
spec:
  containers:
  - name: test
    image: busybox
    command: ["/bin/sh", "-c", "echo 'cephfs OK' > /data/test.txt && cat /data/test.txt && sleep 60"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: test-pvc-cephfs
  restartPolicy: Never
