[all]
k8s-master ansible_host=192.168.56.10 ip=192.168.56.10 vagrant_machine_name=k8s-master-rocky9 vagrant_hostname=k8s-master vagrant_cpus=3 vagrant_memory_mb=3500 vagrant_ssh_port=10030 ansible_ssh_private_key_file=/vagrant/.vagrant/machines/k8s-master-rocky9/virtualbox/private_key
k8s-worker1 ansible_host=192.168.56.21 ip=192.168.56.21 vagrant_machine_name=k8s-worker1-rocky9 vagrant_hostname=k8s-worker1 vagrant_cpus=2 vagrant_memory_mb=3000 vagrant_ssh_port=10041 vagrant_disk_gb=10 rook_device=/dev/sdb ansible_ssh_private_key_file=/vagrant/.vagrant/machines/k8s-worker1-rocky9/virtualbox/private_key
k8s-worker2 ansible_host=192.168.56.22 ip=192.168.56.22 vagrant_machine_name=k8s-worker2-rocky9 vagrant_hostname=k8s-worker2 vagrant_cpus=2 vagrant_memory_mb=3000 vagrant_ssh_port=10042 vagrant_disk_gb=10 rook_device=/dev/sdb ansible_ssh_private_key_file=/vagrant/.vagrant/machines/k8s-worker2-rocky9/virtualbox/private_key
k8s-worker3 ansible_host=192.168.56.23 ip=192.168.56.23 vagrant_machine_name=k8s-worker3-rocky9 vagrant_hostname=k8s-worker3 vagrant_cpus=2 vagrant_memory_mb=3000 vagrant_ssh_port=10043 vagrant_disk_gb=10 rook_device=/dev/sdb ansible_ssh_private_key_file=/vagrant/.vagrant/machines/k8s-worker3-rocky9/virtualbox/private_key

[kube_control_plane]
k8s-master

[control_plane:children]
kube_control_plane

[etcd]
k8s-master

[kube_node]
k8s-worker1
k8s-worker2
k8s-worker3

[workers:children]
kube_node

[storage]
k8s-worker1
k8s-worker2
k8s-worker3

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
cluster_name=k8s-rocky9-cephfs
vagrant_box=bento/rockylinux-9
vagrant_box_version=202510.26.0
node_network_cidr=192.168.56.0/24
kube_network_plugin=flannel
flannel_version=v0.22.0
kube_pods_subnet=10.244.0.0/16
kube_service_addresses=10.96.0.0/12
kube_version=v1.29.5
kubespray_version=v2.25.0
kubespray_git_commit=7e0a40725067f7818bb0cd4acaf27a6620af6e3f
etcd_kubeadm_enabled=true
metrics_server_enabled=true
helm_enabled=true
metallb_enabled=true
metallb_speaker_enabled=true
metallb_version=v0.13.9
metallb_address_pool_cidr=192.168.56.128/28
python_version=3.11.9
python_source_sha256=e7de3240a8bc2b1e1ba5c81bf943f06861ff494b69fda990ce2722a504c6153d
rook_version=v1.14.8
rook_git_commit=35b3b9e4caf1f1b44e30378e7ede5ed2baf08e0c
ceph_image=quay.io/ceph/ceph:v18.2.2
rook_mon_count=3
rook_mgr_count=1
jenkins_git_commit=0c3fba187adbc96c78d9c1dc60e11cdd176ca45b
jenkins_image=jenkins/jenkins:2.452.2-lts-jdk17
jenkins_storage_node=k8s-worker1
prometheus_chart_version=25.22.0
grafana_chart_version=8.2.1
monitoring_storage_class=rook-ceph-block
