[all]
k8s-master ansible_host=192.168.56.10 ip=192.168.56.10 ansible_ssh_private_key_file=/home/vagrant/.ssh/k8s-master_key vagrant_ssh_port=22000
k8s-worker1 ansible_host=192.168.56.21 ip=192.168.56.21 ansible_ssh_private_key_file=/home/vagrant/.ssh/k8s-worker1_key vagrant_ssh_port=22001
k8s-worker2 ansible_host=192.168.56.22 ip=192.168.56.22 ansible_ssh_private_key_file=/home/vagrant/.ssh/k8s-worker2_key vagrant_ssh_port=22002
k8s-worker3 ansible_host=192.168.56.23 ip=192.168.56.23 ansible_ssh_private_key_file=/home/vagrant/.ssh/k8s-worker3_key vagrant_ssh_port=22003

[kube_control_plane]
k8s-master

[etcd]
k8s-master

[kube_node]
k8s-worker1
k8s-worker2
k8s-worker3

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=vagrant
kubespray_version=v2.31.0
kube_version=1.35.4
rook_version=v1.20.0
kube_network_plugin=flannel
kube_pods_subnet=10.244.0.0/16
metallb_ip_range=192.168.56.128-192.168.56.143
