- name: /etc/hosts 엔트리 추가
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: >-
      {{ hostvars[item].ansible_host }}
      {{ hostvars[item].ec2_tags.Name | regex_replace('k8s-storage-lab-', '') }}
    state: present
  loop: "{{ groups['all'] }}"
