apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  storageClassName: rook-ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-test-pod-1
spec:
  containers:
    - name: cephfs-container
      image: busybox:1.37.0
      command: ["sh", "-c", "echo 'Hello from Pod 1' > /mnt/cephfs/pod1.txt; sleep 3600"]
      volumeMounts:
        - mountPath: /mnt/cephfs
          name: cephfs-storage
  volumes:
    - name: cephfs-storage
      persistentVolumeClaim:
        claimName: cephfs-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-test-pod-2
spec:
  containers:
    - name: cephfs-container
      image: busybox:1.37.0
      command: ["sh", "-c", "echo 'Hello from Pod 2' > /mnt/cephfs/pod2.txt; sleep 3600"]
      volumeMounts:
        - mountPath: /mnt/cephfs
          name: cephfs-storage
  volumes:
    - name: cephfs-storage
      persistentVolumeClaim:
        claimName: cephfs-pvc
